version: '3.1'

services:
  auth:
    build: ./auth
    container_name: auth
    restart: always
    image: auth
    ports:
      - ${authport}:${authport}
    environment:
      - "PORT=${authport}"
      - |
        "MYSQL_URL=${mysqluser}:${mysqlpass}@tcp(${mysqlhost}:${mysqlport})/${mysqldb}?parseTime=true&sql_mode=ansi"
        fi
      - "REDIS_URL=redis://${redisaddr}"

  product:
    build: ./product
    container_name: product
    restart: always
    image: product
    ports:
      - ${productport}:${productport}
    environment:
      - "PORT=${productport}"
      - |
        "MYSQL_URL=${mysqluser}:${mysqlpass}@tcp(${mysqlhost}:${mysqlport})/${mysqldb}?parseTime=true&sql_mode=ansi"
        fi
      - "REDIS_URL=redis://${redisaddr}"

  order:
    build: ./order
    container_name: order
    restart: always
    image: order
    ports:
      - ${orderport}:${orderport}
    environment:
      - "PORT=${orderport}"
      - |
        "MYSQL_URL=${mysqluser}:${mysqlpass}@tcp(${mysqlhost}:${mysqlport})/${mysqldb}?parseTime=true&sql_mode=ansi"
        fi
      - "REDIS_URL=redis://${redisaddr}"